name: Publish Nuget Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Update Version ]
    types:
      - completed

defaults:
  run:
    shell: | # Set the default shell for all commands:
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
env:
  PROJECT_NAME:             'AssemblyAttribute'
  BUILD_CONFIGURATION:      'Release'
  # Important files relative to your REPOSITORY ROOT directory:
  #   - `{PROJECT_NAME}/{PROJECT_NAME}.csproj`
  #   - `{PROJECT_NAME}/{PROJECT_NAME}/bin/{BUILD_CONFIGURATION}/{PROJECT_NAME}.{VERSION}.nupkg`

jobs:
  publish:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v3.0.2
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}

      - name: Pack
        run:  |
              dotnet pack -c ${{ env.BUILD_CONFIGURATION }} ${{ env.PROJECT_NAME }}

      - name: Push to GPR & nuget.org
        run:  |
              Write-Output "","# Pushing to (nuget.org) ..."
              dotnet nuget push */bin/${{env.BUILD_CONFIGURATION}}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
              Write-Output "","# Pushing to (Github Package Registry) ..."
              dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/radj307/index.json"
              dotnet nuget push */bin/${{env.BUILD_CONFIGURATION}}/*.nupkg -k ${{ github.token }} -s https://nuget.pkg.github.com/radj307/index.json --skip-duplicate
        
      - name: Upload Artifact(s)
        uses: actions/upload-artifact@v3.1.1
        with:
          name: nupkg
          path: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg
