name: Publish Nuget Package

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Update Version ]
    types:
      - completed

defaults:
  run:
    shell: |
           pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
env:
  # This assumes that your project file is located at: '{github.workspace}/{PROJECT_NAME}/{PROJECT_NAME}{PROJECT_EXTENSION}'
  PROJECT_NAME:             'AssemblyAttribute'
  BUILD_CONFIGURATION:      'Release'
  REQUESTED_DOTNET_VERSION: '6.x.x'

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v3.0.2
        with:
          source-url: https://nuget.pkg.github.com/<owner>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run:  |
              dotnet build -c ${{ env.BUILD_CONFIGURATION }}

      - name: Pack
        run:  |
              dotnet pack -c ${{ env.BUILD_CONFIGURATION }} ${{ env.PROJECT_NAME }}

      - name: Push to GPR & nuget.org
        run:  |
              dotnet nuget push ${{github.workspace}}/${{env.PROJECT_NAME}}/bin/${{env.BUILD_CONFIGURATION}}/*.nupkg
              dotnet nuget push ${{github.workspace}}/${{env.PROJECT_NAME}}/bin/${{env.BUILD_CONFIGURATION}}/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        
      - name: Upload Artifact(s)
        uses: actions/upload-artifact@v3.1.1
        with:
          name: nupkg
          path: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg
