###
# Name:          UpdateVersion.yml
# Project Lang:  C# (not required)
# Description:   Github actions workflow that runs a PowerShell script to update the version number present in a project's .csproj file.
#                This needs to be done in an entirely separate workflow, otherwise actions/checkout & dotnet get confused by each other and refuse to use the correct version number.
###

env:
  REF:    'main'
  # ^ Set this to the target ref (branch/tag/commit)
  SCRIPT: '${{github.workspace}}/SetVersion.ps1'
  # ^ Set this to the location of the powershell script to run.
  
############################################################
name: 'Update Version'

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+-?**'
  workflow_dispatch:

# Set default windows shell
defaults:
  run:
    shell:  |
            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
jobs:
  # This job is required because C# is assholes and dotnet publish refuses to use the version number set by the SetVersion.ps1 script.
  update-version-number:
    runs-on:  windows-2022
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref:  '${{ env.REF }}'
          fetch-depth:  0
        
      - name:   Run SetVersion.ps1
        run:    |
                cd ${{github.workspace}}
                .\SetVersion.ps1
                
      - name:   Fetch History
        run:    git fetch

      - name:   Push Changes
        run:    |
                cd ${{github.workspace}}
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add -A
                git commit -m "Update .csproj Version Numbers"
                git pull
                git push origin
